### ISSUE TITLE
[PE-D][Tester A] Inconsistency in Error Message 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-3/tp#126]
The issue is on the inconsistency of error message displayed when a large index number is added.

- Current Input: 
uc 9999999999999999999999999999999999999999999 n/alex

- Current Output: 
Invalid command format! 
uc: Updates the details of the person identified by the index number used in the displayed person list. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [n/NAME] [c/CLASS/GROUP] [e/EMAIL] [p/PHONE] [t/TELEGRAM ID] [g/GITHUB ID]
Example: uc 1 p/91234567 e/johndoe@example.com

- Expected Output: 
The person index provided is invalid.

Since there is a validation for invalid userID, is it possible to insert an improvement to this validation such that it can check for inputs that exceeds the maximum amount of ID that this application allows?

For example (this should be the expected output):

![Pasted Graphic 8.png](https://raw.githubusercontent.com/KhoonSun47/ped/main/files/e621b5f5-b6cc-4f51-900a-0e5ad7875af2.png)￼

However (this is the current output):

![Pasted Graphic 9.png](https://raw.githubusercontent.com/KhoonSun47/ped/main/files/ef2977b3-bfd2-4bcb-9dd0-cc0e1486e9d7.png)￼

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: KhoonSun47/ped#2

**Comment by kailashgautham** [comment]
![image](https://github.com/AY2324S2-CS2103T-F14-3/tp/assets/103820198/dd989410-af04-40fe-a7d4-011a40bb75e8)

I think that here it tells the user that it is invalid command... which technically isn't true but we'd only be making it more specific. Note the last point in the screenshot attached. Therefore, we can add this under Planned Enhancements instead.
