### ISSUE TITLE
[PE-D][Tester D] UI: Cannot scroll to bottom

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-3/tp#127]
![Screenshot 2024-04-05 at 4.30.36 PM.png](https://raw.githubusercontent.com/dwangwk/ped/main/files/fcf9b80c-1ceb-4c1a-bdac-a00379116276.png)

Unable to scroll to the bottom of the students page, unable to see past the 7th entry despite having more entries and the scroll bar being at the bottom. This occurs after the ls command is used.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: dwangwk/ped#3

**Comment by kailashgautham** [comment]
Make the right side of the panel scrollable as well
