### ISSUE TITLE
[PE-D][Tester D] UI: Notes truncated

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-3/tp#131]
![Screenshot 2024-04-05 at 4.34.39 PM.png](https://raw.githubusercontent.com/dwangwk/ped/main/files/30e70075-950a-4e78-b669-8e9cf1fd8e88.png)

Notes that are too long are truncated, resulting in the user not being able to view the note information

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: dwangwk/ped#4

**Comment by kailashgautham** [comment]
Long strings with small placeholders has already been covered in your other issue, #123. Will be closing this as duplicate.
