### ISSUE TITLE
[PE-D][Tester B] Missing details in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-3/tp#137]
The UG was very easy to use and follow, however, under the `Features`, example error messages could be added to help users better understand the error messages received.

Example: can add example of an error message when an invalid input was entered.
![image.png](https://raw.githubusercontent.com/agreatdayy/ped/main/files/c9ddbb74-ee6f-4b07-831a-1c809cd533b0.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: agreatdayy/ped#2

**Comment by kailashgautham** [comment]
This isn't a bug, more like an enhancement - adding extra details into the UG that the user doesn't necessarily need. Also, adding error explanations might make it more cluttered. Probably not needed under planned enhancements.
