### ISSUE TITLE
[PE-D][Tester E] Invalid Email Allowed (Invalid Domain)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-3/tp#138]
![image.png](https://raw.githubusercontent.com/nyankoclaws/ped/main/files/d9e1a839-a1f1-4dc6-a26b-59f5cbbc73f1.png)

Edit JSON file as such, with an invalid email.

![image.png](https://raw.githubusercontent.com/nyankoclaws/ped/main/files/f3029d9a-13c8-4e74-a926-ebe11a3f3d91.png)

The application loads it normally.

![image.png](https://raw.githubusercontent.com/nyankoclaws/ped/main/files/ab068b0f-bca7-4af9-b965-ecd592a5b046.png)

But the documentation says it allows only valid email addresses.

The email given, johnd@example is not a valid email address, as it only contains 1 level of domain.
Email addresses require at least both a top and second level domain.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: nyankoclaws/ped#4

**Comment by g-tejas** [comment]
As Prof mentioned [here](https://github.com/nus-cs2103-AY2324S2/forum/issues/707), this doesn't qualify as a fix we can make during 1.4.

> Instead, you can update the UG to match the current behavior (e.g., not mention email validation at all or mention that some level of validation is in place but it is up to the user to ensure the email is valid).
