### ISSUE TITLE
[PE-D][Tester D] UI: Unable to see all notes of a person

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-3/tp#141]
When more than 15 notes are added, the 15th note and onwards are unable to be seen with no option to scroll down

![Screenshot 2024-04-05 at 4.53.49 PM.png](https://raw.githubusercontent.com/dwangwk/ped/main/files/103de717-c6a9-408b-a365-bccd664941da.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: dwangwk/ped#8

**Comment by kailashgautham** [comment]
This is related to the scrolling of the side panel, which is also covered in issue #124. Will be closing this as a duplicate.
