### ISSUE TITLE
[PE-D][Tester A] How to identify which student is absent if they have the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-3/tp#146]
The issue is on viewing the specific CLASS_GROUP for attendance, but with multiples of the same name. The user might find it difficult to know which student is absent from his/her class, since the attendance list did not specify clearly which student is absent.

For example (There are multiple "John Doe", but which "John Doe" is absent?):
![image.png](https://raw.githubusercontent.com/KhoonSun47/ped/main/files/579c5ec8-34cc-41fe-9592-bc4ecb9c27c0.png)

- Current Input:
ls F14

- Current Output:
Listed 5 students from class groups: F14

Maybe one way to identify which student is absent (if they have the same name) is to do colour-coding?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: KhoonSun47/ped#6

**Comment by g-tejas** [comment]
We can work around this by checking each John Doe specifically and find out their attendance individually. So this doesn't qualify as a fix we can do during 1.4
